name: Deploy to Vercel
on:
  push:
    branches:
      - main
env:
  DATABASE_URL: ${{ vars.DATABASE_URL}}
jobs:
  postgres-image:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        volumes:
          - ./postgres:/var/lib/postgresql/data
        options: >-
          --name todos-db
          --restart always
          -d
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Migrations deploy
        run: npx prisma migrate deploy
      - name: Prisma CLI
        run: npx prisma generate
